basePath: /v1
definitions:
  v1.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  v1.ExchangeRequest:
    properties:
      amount:
        minimum: 1
        type: integer
      banknotes:
        items:
          type: integer
        minItems: 1
        type: array
        uniqueItems: true
    required:
    - amount
    - banknotes
    type: object
  v1.ExchangeResponse:
    properties:
      exchanges:
        items:
          items:
            type: integer
          type: array
        type: array
    type: object
host: localhost:8080
info:
  contact:
    name: Andrew
    url: https://t.me/realPointer
  title: Exchange banknotes
  version: 1.0.0
paths:
  /exchange:
    post:
      consumes:
      - application/json
      description: Exchange banknotes
      parameters:
      - description: Exchange request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.ExchangeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.ExchangeResponse'
        "400":
          description: Invalid request body
        "404":
          description: No exchanges found for the given amount and banknotes
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "422":
          description: Invalid exchange request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Internal server error
      summary: Exchange banknotes
      tags:
      - exchange
swagger: "2.0"
